# AdGen Configuration

# General Settings
ad_duration_seconds: 20
output_dir: "outputs"

# Provider Defaults
providers:
  llm: "anthropic" # openai, anthropic
  video: "runwayml" # runwayml, pika, veo3, mock
  audio: "mock" # elevenlabs, openai, mock
  music: "mock" # suno, udio, mock

# LLM Settings
llm:
  openai:
    model: "gpt-4"
    temperature: 0.7
  anthropic:
    model: "claude-sonnet-4-0"
    temperature: 0.7

# Video Generation Settings
video:
  aspect_ratio: "16:9"
  quality: "high"
  runwayml:
    text_to_image_model: "gen4_image"
    image_to_video_model: "gen4_turbo"
    max_duration: 10
    min_duration: 5
    timeout_seconds: 300
    max_scenes: 10 # Allow more scenes, will trim in compose step
  pika:
    model: "1.0"
    max_duration: 15
    min_duration: 3
    max_scenes: 5
  veo3:
    max_duration: 8
    min_duration: 5
    max_scenes: 1 # Single comprehensive clip
    single_clip_mode: true # Generate entire sequence in one clip
    generate_audio: true # Cheaper without audio
    timeout_seconds: 300

# Audio Generation Settings
audio:
  format: "wav"
  sample_rate: 44100
  elevenlabs:
    voice_id: "default"
    stability: 0.5
    similarity_boost: 0.75
  openai:
    voice: "alloy"
    speed: 1.0

# Music Generation Settings
music:
  format: "mp3"
  bitrate: 320
  suno:
    style: "instrumental"
  udio:
    style: "background"

# Human Review Points
review:
  concept_approval: true
  final_approval: true
  auto_proceed: false
